import React from 'react';
import SummaryParagraph from '../SummaryParagraph';
import SubTitle from '../SubTitle';

const sipadan = () => (
<React.Fragment>
<SummaryParagraph>Suite et fin de notre périple en Malaisie lors de cette "croisière" d'une semaine à bord du Celebes Explorer, le seul bateau à proposer cette formule sur Sipadan.</SummaryParagraph>
<SummaryParagraph><img src="/summaries/2013/sipadan/DSC02721.jpg" style={{ maxWidth: '100%'}} alt="Le Celebes Explorer au mouillage dans la baie de Semporna" /></SummaryParagraph>
<SummaryParagraph>Nous repassons donc par la case Semporna, après 45 minutes de speed boat depuis Mabul, et embarquons immédiatement à bord du Celebes qui mouille dans la baie. Il ne nous reste alors plus qu'à nous installer et attendre le reste du groupe, 14 autres plongeurs français dont une accompagnatrice H2o. Le bateau est plutôt spacieux, avec 8 cabines passager réparties sur le pont inférieur et le pont principal, une vaste salle à manger, et un espace repos/solarium sur le pont supérieur. Spacieux donc, mais plus très jeune...</SummaryParagraph>
<SummaryParagraph><img src="/summaries/2013/sipadan/DSC02744.jpg" style={{ maxWidth: '100%'}} alt="Le ponton sur lequel nous venons signer le registre" /></SummaryParagraph>
<SummaryParagraph>Le départ aura lieu au petit matin pour rejoindre Sipadan, située à seulement 14km de Mabul, mais le Celebes étant loin d'être un speed boat, le trajet va durer quelques heures. Arrivés sur zone, il va d'abord nous falloir aller signer le registre - comme chaque matin - le nombre total de plongeurs étant limité à 120 par jour. Tous les centres de plongées du coin (Mabul, Kapalai, Bornéo) se partagent donc ces permis et peuvent en moyenne envoyer 15 personnes par jour plonger sur Sipadan. Dans ces conditions, sur un séjour d'une semaine, vous êtes à peu près sûr de pouvoir venir au moins une journée, voire deux, mais guère plus...Seul le Celebes Explorer apporte l'assurance de plonger 5 jours d'affilée sur l'île, à raison de 4 plongées par jour.</SummaryParagraph>
<SummaryParagraph>Cette limitation à 120 plongeurs par jour a été instaurée par les autorités en 2008, alors que les resorts qui y étaient établis avaient déjà été priés de quitter les lieux en 2004, afin de préserver l'environnement de cette île couverte de forêt vierge. Sipadan, découverte par le commandant Cousteau, est la seule île océanique de Malaisie et offre des tombants vertigineux (600m), ce qui permet d'attirer toute la faune sous-marine qui a fait sa réputation. Ici, les stars ce sont les carangues, les barracudas, les requins, les tortues, les perroquets à bosse et une multitude de poissons tropicaux qui ne manqueront pas d'illuminer nos plongées..</SummaryParagraph>
<SummaryParagraph><img src="/summaries/2013/sipadan/DSC02735.jpg" style={{ maxWidth: '100%'}} alt="Coucher de soleil lors du mouillage de nuit à côté de la plateforme Seaventure" /></SummaryParagraph>
<SummaryParagraph>L'île n'est pas très vaste (seulement 12ha) et les sites de plongée, répartis tout autour, sont très proches les uns des autres. Le Celebes Explorer ne va donc pas trop se déplacer pendant la journée, les mises à l'eau s'effectuant à partir d'une petite annexe, mais dès nos 4 plongées effectuées, nous devrons cependant effectuer la traversée et mouiller sur Mabul, aucun bateau n'étant autorisé à rester sur Sipadan de nuit.</SummaryParagraph>
<SummaryParagraph>Le Celebes propose alors une 5ème plongée de nuit autour de Mabul, où nous effectuerons également nos 3 plongées lors du 6ème et dernier jour de la croisière. C'est dons à Mabul qu'ont été faites les quelques photos "macro" de cette galerie.</SummaryParagraph>
<SummaryParagraph>La première plongée du séjour, dite "Check Dive", va avoir lieu sur "Coral Garden", tombant où nous avons croisé quelques tortues et requins pointe blanches. Les choses sérieuses vont commencer dès la deuxième plongée, sur "Barracuda Point" (tout un programme...).</SummaryParagraph>
<SubTitle>Barracuda Point", site incontournable...</SubTitle>
<SummaryParagraph><img src="/summaries/2013/sipadan/DSC02745.jpg" style={{ maxWidth: '100%'}} alt="La carte des sites de plongée sur Sipadan" /></SummaryParagraph>
<SummaryParagraph>En effet, dès la mise à l'eau nous nous retrouvons en immersion totale dans LE banc de carangues de Sipadan! Même si le banc semble moins imposant que l'année précédente, ça reste particulièrement impressionnant! Les carangues à gros yeux forment un tourbillon autour de nous et les requins pointe blanche sont de la partie avec les imposantes carangues ignobilis, dites carangues à grosse tête. L'instant est magique et nous serions bien restés plus longtemps, mais déjà le guide continue son chemin le long du tombant.</SummaryParagraph>
<SummaryParagraph>Au bout de quelques minutes, après avoir croisé quelques requins, nous remontons au-dessus du tombant pour arriver dans une petite vallée à l'aspect quelque peu lunaire, dans un léger courant. Et c'est le deuxième moment fort de cette plongée: les barracudas sont là! Un véritable défilé qui s'étale sur plusieurs dizaines de mètres et remonte doucement le courant...</SummaryParagraph>
<SummaryParagraph>Barracuda point est véritablement LE site mythique et incontournable de Sipadan. Nous l'avons fait 10 fois au cours du séjour, sans jamais nous en lasser, les plongées étant toujours différentes, en fonction du courant, de l'heure, du nombre de plongeurs, etc.</SummaryParagraph>
<SummaryParagraph>Lors de notre deuxième plongée sur ce site, alors que nous attendions les barracudas qui ne se sont pas montrés cette fois là, nous sommes tout simplement tombés sur le banc de perroquets à bosse, quasiment immobile sur le platier, alors que le courant était cette fois un peu plus soutenu...Ce banc est, avec les barracudas et les carangues, l'une des principales attractions de Sipadan.</SummaryParagraph>
<SummaryParagraph>Nous avons eu 3 fois l'occasion de croiser ce banc de perroquets entier, qui se compose de plusieurs dizaines d'individus, certains particulièrement imposants, et la dernière fut la plus spectaculaire: nous évoluions tranquillement le long du tombant de "Staghorn Crest" lorsque nous nous sommes retrouvés nez à nez avec le banc complet qui cette fois nageait à vive allure...Le fait de voir passer ces colosses tout autour de nous est une expérience véritablement impressionnante. Ils dégagent une telle impression de puissance! Peut-être pourrais-je oser la comparaison avec un troupeau de buffle chargeant dans la savanne, avec vous au milieu!</SummaryParagraph>
<SummaryParagraph>Le perroquet à bosse reste tout de même craintif vis à vis des plongeurs, et ces magnifiques poissons nous ont littéralement aspergés d'excrément, laissant derrière eux un véritable nuage de sable en suspension. En effet, il se nourrit principalement de coraux (polypes coralliens + algues symbiotiques microscopique) et rejette donc le squelette calcaire qu'il a finement broyé, c'est à dire du sable...</SummaryParagraph>
<SummaryParagraph>Une autre plongée mémorable s'est déroulée sur "Barracuda Point" lorsque nous avons eu la surprise de voir les barracudas alors qu'il n'y avait pas de courant à ce moment là. Ils sont arrivés en une longue procession qui a commencé à s'enrouler sur elle-même pour former une véritable "boule", puis un "cône" - ou formation dite du "Kebab" - pour enfin se dérouler et s'enrouler à nouveau...Quel spectacle! (voir les photos N°56 à N°60).</SummaryParagraph>
<SummaryParagraph><img src="/summaries/2013/sipadan/DSC02760.jpg" style={{ maxWidth: '100%'}} alt="Sipadan à marée basse" /></SummaryParagraph>
<SummaryParagraph>Vous l'aurez compris, comme toute personne ayant plongé à Sipadan, nous avons été comblés et ne saurons que trop vous conseiller de venir plonger à bord du Celebes Explorer pour en profiter pleinement. Si vous optez pour une autre formule nous risquez de ne venir plonger qu'une journée et aurez alors peut-être la chance de voir tout ce que nous avons pu voir, ou pas...</SummaryParagraph>
<SummaryParagraph>Par contre faites bien attention à vos affaires au début et à la fin du séjour, lorsque le Celebes Explorer mouille dans la baie de Semporna. Pendant la dernière nuit, deux personnes de notre groupe se sont fait voler leur sac de plongée qui était entreposé à l'arrière du bateau...</SummaryParagraph>
</React.Fragment>
);

export default sipadan;
