import React from 'react';
import SummaryParagraph from '../../SummaryParagraph';

const bandasea = () => (
<React.Fragment>
    <SummaryParagraph>Apr&egrave;s 3 jours de Muck Dive au Maluku Divers Resort, nous avons donc embarqu&eacute; sur le <a href="http://www.piratesbaycroisiere.fr/bateaux/categorie-basique/lambo.html" target="_blank" rel="noreferrer">Lambo</a> pour une croisi&egrave;re qui va nous mener jusqu'&agrave; Misool, en passant par Nusa Laut, Les &Icirc;les Banda et l'&Icirc;le Koon.</SummaryParagraph>
    <SummaryParagraph>La premi&egrave;re journ&eacute;e &agrave; bord va &ecirc;tre consacr&eacute;e &agrave; 3 plong&eacute;es suppl&eacute;mentaires dans la baie de Ambon, dont une plong&eacute;e Muck classique qui nous a permis de rendre une derni&egrave;re visite aux Rhinopias du coin et la fameuse plong&eacute;e sur Twilight zone (voir article pr&eacute;c&eacute;dent sur Ambon).</SummaryParagraph>
    <SummaryParagraph>Le lendemain matin nous levons l'ancre pour une courte navigation vers Nusa Laut, &agrave; une quarantaine de milles &agrave; l'est de Ambon, o&ugrave; nous allons plonger pour la journ&eacute;e. Nous y d&eacute;couvrirons des r&eacute;cifs et tombants particuli&egrave;rement poissonneux et riches en coraux durs divers et vari&eacute;s.</SummaryParagraph>
    <SummaryParagraph>C'est ensuite une navigation de plus de 80 milles en pleine mer qui nous attend pour atteindre l'archipel des Banda, c&eacute;l&egrave;bre pour ses &eacute;pices, et plus particuli&egrave;rement la noix de muscade. Apr&egrave;s les Portugais et les Anglais, ce sont les Hollandais qui s'imposent dans l'archipel au d&eacute;but du 17&egrave;me si&egrave;cle et qui par la m&ecirc;me occasion tentent d'obliger les habitants &agrave; leur donner l'exclusivit&eacute; du commerce des &eacute;pices. Cette exclusivit&eacute; ne sera pas respect&eacute;e, ce qui provoqua la fureur des Hollandais et de terribles repr&eacute;sailles puisqu'ils louèrent les services de Samoura&iuml;s japonais afin d'assassiner tous les notables de l'&icirc;le.</SummaryParagraph>
    <SummaryParagraph textAlign="center">
        <img style={{marginTtop: '5px', marginBottom: '5px', maxWidth: '100%'}} src="/summaries/2014/misool/banda.jpg" alt="banda" />
    </SummaryParagraph>
    <SummaryParagraph>Si vous passez un jour dans le coin, prenez le temps d'aller &agrave; terre pour visiter le fort de Banda Neira et ce petit mus&eacute;e dans lequel vous aurez l'occasion de voir un tableau repr&eacute;sentant ce massacre particuli&egrave;rement sanglant.</SummaryParagraph>
    <SummaryParagraph>Si vous n'avez pas peur de vous lever tôt, n'hésitez pas non plus à gravir le volcan sur l'île de Banda Api, qui fait face à Banda Neira, pour aller admirer le lever de soleil sur l'archipel (mais pas fait...)</SummaryParagraph>
    <SummaryParagraph>La dernière éruption de ce volcan ne date que de 1988. Une coulée de lave s'est alors répandue dans la mer, au nord de l'île, engloutissant totalement les fonds marins. Mais 26 ans plus tard, la surprise est totale...'Lava Flow' est un site de plongée incontournable où les coraux durs ont repoussé comme nulle part ailleurs. La couche de lave aura donc été un support plus qu'idéal pour le développement de coraux de toutes sortes, à tel point que certaines tables d'Acropora de belle taille se sont déjà développées sur d'anciennes tables effondrées sous leur propre poids!</SummaryParagraph>
    <SummaryParagraph>Batu Kapal est un autre site remarquable à l'est de l'archipel, légèrement au large. Il s'agit d'un sec dont le sommet culmine à 5-10m de profondeur. Dès la mise à l'eau, le spectacle est total! Nous sommes entourés d'une multitude de poissons tels que balistes, papillons, fusiliers pour les plus petits ou encore napoléons, raies marbrées, murènes, et même un banc de thons qui passera en fin de plongée. Nous retrouvons également une vie fixée exubérante avec des gorgones et des éponges gigantesques, des surplombs gavés de coraux de toutes sortes qui éclatent de milles couleurs...</SummaryParagraph>
    <SummaryParagraph>En marge de ces plongées spectaculaires, nous avons également eu l'occasion d'effectuer deux plongées de nuit pour aller observer les poissons-mandarins (Synchiropus splendidus).</SummaryParagraph>
    <SummaryParagraph>Ces petits poissons de moins d'une dizaine de centimètres (généralement 6 ou 7 cm), de la famille des dragonnets, sont réputés être les plus beaux poissons du monde. Pour les voir, il suffit de se mettre à l'eau juste avant la tombée de la nuit dans une zone peu profonde d'éboulis ou de coraux morts, où ils peuvent se cacher pendant la journée, et d'attendre patiemment...Petit à petit, alors que le crépuscule se transforme en obscurité totale, ils se montrent, d'abord timidement, les mâles à la recherche de leur promise d'un soir, toutes nageoires déployées. Puis quand les couples se sont trouvés, voilà que la parade nuptiale commence. Le mâle et la femelle se collent l'un à l'autre, flanc conte flanc, s'élèvent en pleine eau vers la surface, puis se séparent et retourne sur le fond. Ce petit manège va se répéter plusieurs fois, sans même que les flashs de nos appareils ne les perturbent (tout du moins en apparence). Le but ultime de la manœuvre étant bien-sûr l'expulsion des œufs de la femelle et leur fécondation immédiate par le mâle.</SummaryParagraph>
    <SummaryParagraph>Mais attention, le timing est très important. Le spectacle commence à la tombée de la nuit et ne dure qu'une trentaine de minutes (cf. photos 9, 10 et 21).</SummaryParagraph>
    <SummaryParagraph>Après deux jours sur l'archipel des Banda, nous nous dirigeons maintenant vers l'île Koon, à l'extrême est de Seram (la grande île juste au-dessus de Ambon). Là, le spectacle se concentre dans le bleu avec dans le désordre des mérous, des carangues, des thons à dents de chien, des barracudas, des chirurgiens et j'en passe...</SummaryParagraph>
    <SummaryParagraph>Enfin, pour les 4 derniers jours de la croisière, nous arrivons sur Misool, l'île la plus au sud de l'archipel des Raja Ampat, pour un bouquet final mémorable...</SummaryParagraph>
    <SummaryParagraph>Dès la première plongée, c'est effectivement un véritable feu d'artifice aussi bien dans le bleu avec des nuées impressionnantes d'anchois que sur les parois des récifs qui regorgent de coraux de toutes les couleurs, avec des alcyonaires et autres gorgones à profusion. Et bien entendu, la nature étant ce qu'elle est, cette abondance d'anchois attire bon nombre de prédateurs tels les raies mobula qui chassent en escadron. Bref, Misool aura tenu toutes ses promesses, et pas une plongée ici n'aura été un ton en-dessous d'une autre. Il y en avait vraiment pour tous les goûts, et même si je n'ai pas sorti l'objectif macro, les hippocampes pygmées étaient bien là, à chaque plongée dans les gorgones, tout comme le fameux Wobbegong (requin-tapis) qui s'est tout de même fait un peu plus discret.</SummaryParagraph>
</React.Fragment>
)

export default bandasea